### ISSUE TITLE
Quick question about examples chat.

### ISSUE THREAD

**Issue by qwexvf** [r0fls/sanic-websockets#1]
when i access to / i got 

```
2017-02-16 21:53:26,266: ERROR: Traceback (most recent call last):
  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.5/site-packages/sanic/sanic.py", line 320, in handle_request
    handler, args, kwargs = self.router.get(request)
  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.5/site-packages/sanic/router.py", line 266, in get
    return self._get(request.url, request.method, '')
  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.5/site-packages/sanic/router.py", line 311, in _get
    raise NotFound('Requested URL {} not found'.format(url))
sanic.exceptions.NotFound: Requested URL / not found

2017-02-16 21:53:26,404: ERROR: Traceback (most recent call last):
  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.5/site-packages/sanic/static.py", line 54, in _handler
    stats = await stat(file_path)
  File "/home/qwexvf/.pyenv/versions/3.5.2/lib/python3.5/asyncio/coroutines.py", line 209, in coro
    res = yield from res
  File "uvloop/future.pyx", line 230, in __iter__ (uvloop/loop.c:110600)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/home/qwexvf/.pyenv/versions/3.5.2/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: './favicon.ico'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.5/site-packages/sanic/sanic.py", line 329, in handle_request
    response = await response
  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.5/site-packages/sanic/static.py", line 65, in _handler
    relative_url=file_uri)
sanic.exceptions.FileNotFound: File not found
```
*ignore the favicon error.
Any Suggestions ?

**Comment by r0fls** [comment]
@qwexvf try `/chat.html` instead of just `/`. It's using the `static` method to serve a directory here: https://github.com/r0fls/sanic-websockets/blob/master/examples/chat/chat.py#L28

So, you need to use the path to the file.
